version: '3.8'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gerador_diplomas
    ports:
      - "5432:5432"
    volumes:
      - ./db_postgres/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - app-network
      
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network
    volumes:
      - ./worker:/app

networks:
  app-network:
    driver: bridge
